name: CI

on:
  push:
    branches: [main]
    paths:
      - "**.rs"
      - "Cargo.toml"
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: fmt check
        run: cargo fmt --all -- --check
      - name: cargo check
        run: cargo check
      - name: tests/benches
        run: cargo test --benches --all
